# <font color='orange'>Converting the json file to cvs

In [1]:
import pandas as pd

In [2]:
df=pd.read_json('United-States.json')
df

                 type                                           features
0   FeatureCollection  {'type': 'Feature', 'id': 'AL', 'properties': ...
1   FeatureCollection  {'type': 'Feature', 'id': 'AK', 'properties': ...
2   FeatureCollection  {'type': 'Feature', 'id': 'AZ', 'properties': ...
3   FeatureCollection  {'type': 'Feature', 'id': 'AR', 'properties': ...
4   FeatureCollection  {'type': 'Feature', 'id': 'CA', 'properties': ...
5   FeatureCollection  {'type': 'Feature', 'id': 'CO', 'properties': ...
6   FeatureCollection  {'type': 'Feature', 'id': 'CT', 'properties': ...
7   FeatureCollection  {'type': 'Feature', 'id': 'DE', 'properties': ...
8   FeatureCollection  {'type': 'Feature', 'id': 'FL', 'properties': ...
9   FeatureCollection  {'type': 'Feature', 'id': 'GA', 'properties': ...
10  FeatureCollection  {'type': 'Feature', 'id': 'HI', 'properties': ...
11  FeatureCollection  {'type': 'Feature', 'id': 'ID', 'properties': ...
12  FeatureCollection  {'type': 'Feature', 'id': 'IL', 'properties': ...
13  FeatureCollection  {'type': 'Feature', 'id': 'IN', 'properties': ...
14  FeatureCollection  {'type': 'Feature', 'id': 'IA', 'properties': ...
15  FeatureCollection  {'type': 'Feature', 'id': 'KS', 'properties': ...
16  FeatureCollection  {'type': 'Feature', 'id': 'KY', 'properties': ...
17  FeatureCollection  {'type': 'Feature', 'id': 'LA', 'properties': ...
18  FeatureCollection  {'type': 'Feature', 'id': 'ME', 'properties': ...
19  FeatureCollection  {'type': 'Feature', 'id': 'MD', 'properties': ...
20  FeatureCollection  {'type': 'Feature', 'id': 'MA', 'properties': ...
21  FeatureCollection  {'type': 'Feature', 'id': 'MI', 'properties': ...
22  FeatureCollection  {'type': 'Feature', 'id': 'MN', 'properties': ...
23  FeatureCollection  {'type': 'Feature', 'id': 'MS', 'properties': ...
24  FeatureCollection  {'type': 'Feature', 'id': 'MO', 'properties': ...
25  FeatureCollection  {'type': 'Feature', 'id': 'MT', 'properties': ...
26  FeatureCollection  {'type': 'Feature', 'id': 'NE', 'properties': ...
27  FeatureCollection  {'type': 'Feature', 'id': 'NV', 'properties': ...
28  FeatureCollection  {'type': 'Feature', 'id': 'NH', 'properties': ...
29  FeatureCollection  {'type': 'Feature', 'id': 'NJ', 'properties': ...
30  FeatureCollection  {'type': 'Feature', 'id': 'NM', 'properties': ...
31  FeatureCollection  {'type': 'Feature', 'id': 'NY', 'properties': ...
32  FeatureCollection  {'type': 'Feature', 'id': 'NC', 'properties': ...
33  FeatureCollection  {'type': 'Feature', 'id': 'ND', 'properties': ...
34  FeatureCollection  {'type': 'Feature', 'id': 'OH', 'properties': ...
35  FeatureCollection  {'type': 'Feature', 'id': 'OK', 'properties': ...
36  FeatureCollection  {'type': 'Feature', 'id': 'OR', 'properties': ...
37  FeatureCollection  {'type': 'Feature', 'id': 'PA', 'properties': ...
38  FeatureCollection  {'type': 'Feature', 'id': 'RI', 'properties': ...
39  FeatureCollection  {'type': 'Feature', 'id': 'SC', 'properties': ...
40  FeatureCollection  {'type': 'Feature', 'id': 'SD', 'properties': ...
41  FeatureCollection  {'type': 'Feature', 'id': 'TN', 'properties': ...
42  FeatureCollection  {'type': 'Feature', 'id': 'TX', 'properties': ...
43  FeatureCollection  {'type': 'Feature', 'id': 'UT', 'properties': ...
44  FeatureCollection  {'type': 'Feature', 'id': 'VT', 'properties': ...
45  FeatureCollection  {'type': 'Feature', 'id': 'VA', 'properties': ...
46  FeatureCollection  {'type': 'Feature', 'id': 'WA', 'properties': ...
47  FeatureCollection  {'type': 'Feature', 'id': 'WV', 'properties': ...
48  FeatureCollection  {'type': 'Feature', 'id': 'WI', 'properties': ...
49  FeatureCollection  {'type': 'Feature', 'id': 'WY', 'properties': ...

In [3]:
df.to_csv('United-States.csv')

In [4]:
df1=pd.read_csv('United-States.csv',delimiter=',')

In [5]:
df1.head()

,Unnamed: 0,type,features
0,0,FeatureCollection,"{'type': 'Feature', 'id': 'AL', 'properties': ..."
1,1,FeatureCollection,"{'type': 'Feature', 'id': 'AK', 'properties': ..."
2,2,FeatureCollection,"{'type': 'Feature', 'id': 'AZ', 'properties': ..."
3,3,FeatureCollection,"{'type': 'Feature', 'id': 'AR', 'properties': ..."
4,4,FeatureCollection,"{'type': 'Feature', 'id': 'CA', 'properties': ..."